### ISSUE TITLE
Validate compatibility with Swift C++ interoperability in CI

### ISSUE THREAD

**Issue by bauer-andreas** [StanfordBDHG/ResearchKit#13]
### Problem

With #12 we fixed some compilation issues that occurred when trying to use ResearchKit in an application that uses C++ interoperability. We currently don't verify this scenario within the CI and this might result in regressions in the future.

### Solution

Set up a test `Package.swift` that enables swift C++ interoperability (or can we just pass a compiler flag for the `SWIFT_OBJC_INTEROP_MODE ` with the CI?) when building a package that depends on the ResearchKit binary target.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Great idea @Supereg; that would be a good follow up @philippzagar 👍

**Comment by philippzagar** [comment]
Tackled by #14
