### ISSUE TITLE
Sync with ResearchKit 3.0 released 4/28/24

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [StanfordBDHG/ResearchKit#25]
### Problem

ResearchKit got a 3.0 version rev, yesterday. But alas, no Swift Package support 😦 .
https://github.com/ResearchKit/ResearchKit
https://github.com/ResearchKit/ResearchKit/releases/tag/3.0

Please update your package compatible fork.

### Solution

Sync with ResearchKit/ResearchKit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Thank you for sharing the issue @SwiftNativeDeveloper!

Would you be interested in creating a PR that updates the repo to the new ResearchKit 3.0 release? Contributions are always more than welcome 👍

**Comment by SwiftNativeDeveloper** [comment]
I'm trying to push the thread over here and via apple feedbacks: https://github.com/ResearchKit/ResearchKit/issues/1111#issuecomment-2027382155

Unfortunately, I don't have the bandwidth to contribute a change like this. I assume it is heavily involved since Apple split the library into ResearchKit and ResearchKitUI so it would be a simple number rev like the previous updates on your repo have been.

**Comment by PSchmiedmayer** [comment]
@SwiftNativeDeveloper Thank you for pushing this in the Apple repo as well; it's always good to raise challenges you and any other developer in the RK community are having!

We are developing the RK fork on our spare time without any explicit funding through a research project or financial support from Apple so our bandwidth is also capped and we are focusing in our own Spezi packages.
Nevertheless, we always try to do our best to support the open-source community and larger digital-health ecosystem with, e.g., this RK fork and our other open-source tools.
Our bandwidth is also capped and we are looking for people and support at this point but I will see how and when we might be able to take a look at this and put it on our timeline.

**Comment by PSchmiedmayer** [comment]
It was a decent merge conflict but we have update the repo to RK 3.0.
